resolver: lts-12.13
packages:
- .
extra-deps:
  - hakyll-sass-0.2.3
  - numerals-0.4.1
  - https://github.com/abhin4v/thumbnail-plus/archive/fc10600d3af19ccce7c69416e2ec33143faa4d37.zip
  - https://github.com/abhin4v/hakyll/archive/997297fda88a7ea0caa724b3064776b4d247d203.zip
flags: {}
extra-package-dbs: []
