resolver: lts-12.21
packages:
- .
extra-deps:
  - hakyll-sass-0.2.3
  - numerals-0.4.1
  - https://github.com/abhin4v/thumbnail-plus/archive/fc10600d3af19ccce7c69416e2ec33143faa4d37.zip
  - https://github.com/jaspervdj/hakyll/archive/a7f72c5ab15862cb344ee5d7d81e128d0c5e8f85.zip
flags: {}
extra-package-dbs: []
