resolver: lts-10.2
packages:
- .
extra-deps:
  - https://github.com/jaspervdj/hakyll/archive/480da307d22aff8ab3817d1586710c5f4ff6d779.zip
  - hakyll-sass-0.2.3
  - feed-0.3.12.0
flags: {}
extra-package-dbs: []
